//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v3.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Collections.Generic;

using MagicEastern.ADOExt;
namespace Test
{
    [DBTable(TableName = "SalesOrderHeader", Schema = "Sales")]
    public partial class SalesOrderHeader
    {

        [DBColumn]
        public virtual System.String AccountNumber
        {
            get; set;
        }


        [DBColumn]
        public virtual System.String Comment
        {
            get; set;
        }


        [DBColumn]
        public virtual System.String CreditCardApprovalCode
        {
            get; set;
        }

        [DBColumn(Required = true)]
        public virtual System.DateTime DueDate
        {
            get; set;
        }


        [DBColumn(Required = true)]
        public virtual System.Decimal Freight
        {
            get; set;
        }


        [DBColumn(Required = true)]
        public virtual System.DateTime ModifiedDate
        {
            get; set;
        }


        [DBColumn(Required = true)]
        public virtual System.Boolean OnlineOrderFlag
        {
            get; set;
        }


        [DBColumn(Required = true)]
        public virtual System.DateTime OrderDate
        {
            get; set;
        }


        [DBColumn]
        public virtual System.String PurchaseOrderNumber
        {
            get; set;
        }


        [DBColumn(Required = true)]
        public virtual System.Byte RevisionNumber
        {
            get; set;
        }


        [DBColumn(Required = true)]
        public virtual System.Guid Rowguid
        {
            get; set;
        }


        [DBColumn(Required = true, NoInsert = true)]
        public virtual System.Int32 SalesOrderId
        {
            get; set;
        }


        [DBColumn(Required = true, NoInsert = true, NoUpdate = true)]
        public virtual System.String SalesOrderNumber
        {
            get; set;
        }

        [DBColumn]
        public virtual Nullable<System.DateTime> ShipDate
        {
            get; set;

        }

        [DBColumn(Required = true)]
        public virtual System.Byte Status
        {
            get; set;
        }

        [DBColumn(Required = true)]
        public virtual System.Decimal SubTotal
        {
            get; set;
        }

        [DBColumn(Required = true)]
        public virtual System.Decimal TaxAmt
        {
            get; set;
        }

        [DBColumn(Required = true, NoInsert = true, NoUpdate = true)]
        public virtual System.Decimal TotalDue
        {
            get; set;
        }

        [DBColumn(Required = true)] public int CustomerID { get; set; }

        [DBColumn] public int? SalesPersonID { get; set; }

        [DBColumn] public int? TerritoryID { get; set; }

        [DBColumn(Required = true)] public int BillToAddressID { get; set; }

        [DBColumn(Required = true)] public int ShipToAddressID { get; set; }

        [DBColumn(Required = true)] public int ShipMethodID { get; set; }

        [DBColumn] public int? CreditCardID { get; set; }

        [DBColumn] public int? CurrencyRateID { get; set; }


    }
}
